services:
  - type: web
    name: iconnet-laravel
    runtime: php
    buildCommand: |
      composer install --no-dev
      php artisan migrate --force
      php artisan config:cache
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromService:
          type: mysql
          name: iconnet-mysql
          property: host
      - key: DB_PORT
        fromService:
          type: mysql
          name: iconnet-mysql
          property: port
      - key: DB_DATABASE
        fromService:
          type: mysql
          name: iconnet-mysql
          property: database
      - key: DB_USERNAME
        fromService:
          type: mysql
          name: iconnet-mysql
          property: user
      - key: DB_PASSWORD
        fromService:
          type: mysql
          name: iconnet-mysql
          property: password

databases:
  - name: iconnet-mysql
    databaseName: iconnet
